CREATE TABLE `User` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Login VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE CHECK (Email LIKE '%@%.%'),
    Phone_Number VARCHAR(20) CHECK (Phone_Number REGEXP '^[0-9]{9}$')  -- 9 digit phone number
);

CREATE TABLE Address (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Street VARCHAR(255),
    Number VARCHAR(10),
    Country VARCHAR(255),
    City VARCHAR(255),
    Zip_Code VARCHAR(20) CHECK (Zip_Code LIKE '%[0-9a-zA-Z -]%'), 
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);


CREATE TABLE Cart (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Total DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (Total >= 0),
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);


CREATE TABLE Cart_Product (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CartID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    FOREIGN KEY (CartID) REFERENCES Cart(ID) ON DELETE CASCADE
    -- FOREIGN KEY (ProductID) REFERENCES Product(ID) ON DELETE CASCADE 
);


CREATE TABLE WishList (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Product_ID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
    -- FOREIGN KEY (Product_ID) REFERENCES Product(ID) ON DELETE CASCADE 
);
